language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk6
before_script: cd katas
notifications:
  slack:
    rooms:
      - leanintuit:4TbhlQX6AdNBl5hTK0PubKnh#engineering_training
    on_success: always
    on_failure: always