matrix:
  include:
    - language: java
      jdk:
        - oraclejdk8
      before_script: cd katas

    - laguage: node_js
      node_js:
        - node
      cache:
        directories:
          - "node_modules"
      before_install:

      install:
        - npm install

      script:
        - node index.js

      notifications:
        email:
          - shawnbutton@gmail.com

